// Editor storage — persists custom languages & editor state in the browser

const EDITOR_KEY = 'gfe_languages';

export function loadEditorLanguages() {
  try { return JSON.parse(localStorage.getItem(EDITOR_KEY) || '[]'); }
  catch { return []; }
}

export function saveEditorLanguages(langs) {
  localStorage.setItem(EDITOR_KEY, JSON.stringify(langs));
}

export function upsertEditorLanguage(lang) {
  const all = loadEditorLanguages();
  const idx = all.findIndex(l => l.id === lang.id);
  if (idx >= 0) all[idx] = lang; else all.push(lang);
  saveEditorLanguages(all);
}

export function deleteEditorLanguage(id) {
  saveEditorLanguages(loadEditorLanguages().filter(l => l.id !== id));
}

// ── Import ────────────────────────────────────────────────────────────────────
// Accepts a GlossForge backup JSON (v2.0) or a bare array of language objects
export function parseImport(jsonString) {
  const data = JSON.parse(jsonString);

  // Full backup format
  if (data.customLanguages && Array.isArray(data.customLanguages)) {
    return { languages: data.customLanguages, source: 'backup', version: data.version };
  }

  // Array of languages directly
  if (Array.isArray(data)) {
    return { languages: data, source: 'array' };
  }

  // Single language object
  if (data.vocabulary && data.id) {
    return { languages: [data], source: 'single' };
  }

  throw new Error('Unrecognised format. Expected a GlossForge backup, language array, or single language object.');
}

// ── Export ────────────────────────────────────────────────────────────────────
// Exports in GlossForge backup format — Android app can restore this directly
export function buildExport(languages) {
  return {
    version: '2.0',
    exportedAt: new Date().toISOString(),
    exportedBy: 'GlossForge Editor (Web)',
    customLanguages: languages,
    // Preserve any existing progress/settings keys the Android app looks for
    progress: {},
    settings: { showPronunciation: true },
    xp: '0',
    streak: '{}',
    achievements: '[]',
    quizCount: '0',
    dailyCount: '0',
  };
}

export function downloadJSON(obj, filename) {
  const blob = new Blob([JSON.stringify(obj, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// Export a single language as a standalone seed JS file (for developers adding to the app)
export function buildSeedFile(lang) {
  const identifier = lang.id.replace(/[^a-zA-Z0-9_]/g, '_');
  const json = JSON.stringify(lang, null, 2);
  return `// GlossForge Language Seed — generated by GlossForge Editor\n// Language: ${lang.name}\nexport const ${identifier} = ${json};\n`;
}
